# Generated by Django 4.2.7 on 2023-11-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='public',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
